stages:
  - test
  - build
  - deploy
unit-test:
  script:
    "/Applications/Unity/Hub/Editor/2018.4.4f1/Unity.app/Contents/MacOS/Unity \
    -batchmode \
    -projectPath . \
    -runTests -testPlatform editmode \
    -logFile \
    -testResults ./unit-tests.xml"
  stage: test
  tags:
    - unity
unity-build:
  script: "echo 'Building...'"
  stage: build
  tags:
    - unity
playstore:
  script: "echo 'Deploying...'"
  stage: deploy
  tags:
    - unity
